WIP Makes the PropertyStateSerializer deal with pint columns
Without this the pint fields default to FloatFields courtesy of
something deep inside RestFramework and throw a DimensionalityError.

```
  File "/vagrant/pyenv/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 508, in da
ta
    ret = super(Serializer, self).data
  File "/vagrant/pyenv/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 240, in da
ta
    self._data = self.to_representation(self.instance)
  File "/vagrant/seed/seed/serializers/properties.py", line 187, in to_representation
    result = super(PropertyViewSerializer, self).to_representation(data)
  File "/vagrant/pyenv/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 477, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/vagrant/pyenv/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 477, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/vagrant/pyenv/local/lib/python2.7/site-packages/rest_framework/fields.py", line 898, in to_repr
esentation
    return float(value)
  File "/vagrant/pyenv/local/lib/python2.7/site-packages/pint/quantity.py", line 451, in __float__
    raise DimensionalityError(self._units, 'dimensionless')
DimensionalityError: Cannot convert from 'foot ** 2' to 'dimensionless'
```